#spring.security.user.name=tess
#spring.security.user.password=tess


# PostgreSQL  Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tess
spring.datasource.username=tess
spring.datasource.password=tess
spring.datasource.driver-class-name=org.postgresql.Driver



server.servlet.session.cookie.same-site=strict
